import type { Metadata } from "next";
import { epilogue } from "@/app/ui/fonts";
import "./globals.css";

import ReduxProvider from "@/app/store/reduxProvider";

export const metadata: Metadata = {
  title: "job listing application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
